# Site settings
title: Amber Frid-Jimenez
#email: your-email@domain.com
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#url: "http://yourdomain.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

permalink: none

exclude:
  - package.json
  - node_modules
  - gulpfile.js

sass:
  sass_dir: css
  #style: css/main

keep_files:
#  - _site/css
  - _site/js

include: ['_pages']
